server:
  port: 8082
spring:
  application:
    name: topeducation-ms2
  datasource:
    url: jdbc:mysql://localhost:3307/topeducation_db_2
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
