server:
  port: 8083
spring:
  application:
    name: topeducation-ms3
  datasource:
    url: jdbc:mysql://localhost:3308/topeducation_db_3
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update