apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deployment
  labels:
    app: config-server-deployment
spec:
  selector:
    matchLabels:
      app: config-server-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: config-server-deployment
    spec:
      containers:
        - name: config-server
          image: polloh/config-server:latest
          ports:
            - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: config-server-service
  labels:
    app: config-server-service
spec:
  selector:
    app: config-server-deployment
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: LoadBalancer