version: "3.8"
services:
  mysql-db:
    container_name: topeducation_mysql_container
    image: mysql
    restart: always
    volumes:
      - ./mysql-dump/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: topeducation
    ports:
      - 33060:3306
  app:
    container_name: topeducation_spring_container
    image: polloh/topeducation_spring
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/topeducation?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql-db
