pipeline{
    agent any
    tools{
        maven "maven"
    }
    stages{
        stage("Build JAR File"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/hector-gallard0/proyecto-mingeso']])
                dir("topeducation"){
                    sh "mvn clean install"
                }
            }
        }
        stage("Test"){
            steps{
                dir("topeducation"){
                    sh "mvn test"
                }
            }
        }
        stage("Build Docker Image"){
            steps{
                dir("topeducation"){
                    sh "sudo docker build -t polloh/topeducation_spring ."
                }
            }
        }
        stage("Push Docker Image"){
            steps{
                dir("topeducation"){
                    withCredentials([string(credentialsId: 'dckrhubpassword', variable: 'dckpass')]){
                        sh "docker login -u polloh -p ${dckpass}"

                    }
                    sh "sudo docker push polloh/topeducation_spring"
                }

            }
        }
    }
    post{
        always{
            dir("topeducation"){
                sh "docker logout"
            }
        }
    }
}