server:
  port: 8084
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/hector-gallard0/proyecto-mingeso
          search-paths: config-data
  application:
    name: config-server